### PR TITLE
Switch eck_sub_types OptionGroup to a managed entity

### PR DESCRIPTION
**Pull request by colemanw**
This answers [@jensschuppe's question](https://github.com/systopia/de.systopia.eck/pull/30#issuecomment-1058113057) about how to create an option group using the _CiviCRM Managed_ system.

**NOTES:**

- Placing it in a `.mgd.php` file is standard. #30 worked directly in the hook code because it needed some logic to loop through the entitiy types. But normally the hook just scans this directory for `.mgd.php` files and returns their contents.
- Before this PR I think the optionGroup was getting created on install, but I don't see anywhere it was getting deleted on uninstall. This PR fixes that, because I set `cleanup => always` so it will get auto-deleted on uninstall.
- After this change the `CRM_Eck_CustomData` class is no longer used so I removed it. I assume it was copied over from another extension because it's quite large.
- As usual, the only tricky part about this is managing upgrades. Once again this will crash the upgrader unless you manually delete the existing record. But again, there's only one site in the world using this extension, so maybe that's not too hard to do?
- I autogenerated the contents of the `.mgd.php` file with the API Explorer. It's pretty cool:

image

### CODE REVIEW

**Comment by colemanw** [comment]
This core patch should help make this sort of upgrade problem much easier in the future: https://github.com/civicrm/civicrm-core/pull/22883

**Comment by jensschuppe** [comment]
Sorry for 92fc9801f8e9ba0ca6b096c657c039d5a3af7482 and 89dafe192afc90f843dce84e3ff62afedcc3e4a4 - explicitly creating managed entity records doesn't seems robust enough if extension upgrades are not running _before_ a cache clear / menu rebuild that causes managed entities be reconciled. I'll merge this unchanged.

**Comment by colemanw** [comment]
@jensschuppe right, unfortunately that doesn't work because the managed reconciliation happens *before* the upgrader runs.
I'm not quite sure why. But I think https://github.com/civicrm/civicrm-core/pull/22883 is the best solution in the future.

**Comment by jensschuppe** [comment]
This is what needs to be done before reconciling managed entities with this PR:

```php
// Create managed entity for previously unmanaged eck_sub_types OptionGroup.
\Civi\Api4\Managed::create(FALSE)
  ->setValues([
                'module' => E::LONG_NAME,
                'name' => 'OptionGroup_eck_sub_types',
                'cleanup' => 'always',
                'entity_type' => 'OptionGroup',
                'entity_id' => \Civi\Api4\OptionGroup::get(FALSE)
                  ->addSelect('id')
                  ->addWhere('name', '=', 'eck_sub_types')
                  ->execute()
                  ->single()['id'],
              ])
  ->execute();
```

**Comment by jensschuppe** [comment]
It depends on how you update the extension. Just dropping in the new code and running upgrades manually via the UI doesn't cause managed entities be reconciled until a manually triggered cache clear / menu rebuild. I'm not sure about `cv` though.

That might still be a problem causing managed entities not being created when they're missing (i.e. come new with an update or in a more complicated scenario as ours). But that's a thing for core, I guess. @colemanw do you know when managed entities are being reconciled in the first place?

**Comment by colemanw** [comment]
My understanding is that managed entities get reconciled every time you do a full cache-clear, and at the end of every upgrade. I'm not sure why it's been happening for me *before* the upgrade runs (I've been using `cv`). This extension also triggers it manually whenever an entityType is saved or deleted:
https://github.com/systopia/de.systopia.eck/blob/2d3756d8534c8f3a2e858e6101d3a6672d20c68d/eck.php#L279-L281

**Pull request merged**
