### PR TITLE
Fix display of option fields in entity view

### PR DESCRIPTION
**Pull request by dontub**
This makes the values (i.e. the option labels) of fields referencing an option group visible in the entity view. Before no value was shown for those fields.

As added as todo, the view should be migrated to SearchKit.

### CODE REVIEW

**Review by jensschuppe — APPROVED** [review]

**Comment by jensschuppe** [comment]
@colemanw Feel free to leave your thoughts, regardless of the merge.

**Comment by colemanw** [comment]
Agree it would be good to start replacing stuff like this with SK/FB but those tools don't come with a quick & easy "view 1 record" mode yet. It would be nice to add something along those lines.

**Comment by jensschuppe** [comment]
There could at least be a *SearchKit* search per entity type with all entity fields (including custom fields), a "List" display and a *FormBuilder* display with a URL filter for the entity ID - both will have to be updated though, once a custom field is added/deleted/altered, I guess …

Maybe a first step towards a generic entity display would be a *SearchKit* display type that does not imply any HTML markup (as *Table*, *List* and *Grid* currently do), and build upon that for auto-updating *SearchKit* searches etc.

**Comment by colemanw** [comment]
> both will have to be updated though, once a custom field is added/deleted/altered, I guess

That won't require an update as these things are generated on-the-fly so will always be up-to-date with the current list of custom fields. This is the code that fetches all eck fields + custom fields to create the "add/edit" Afform for an ECK subtype:

https://github.com/systopia/de.systopia.eck/blob/956e945462e20281654ca4f58f26c90c7e701d6b/Civi/Eck/API/Entity.php#L132-L141

**Pull request merged**
