### PR TITLE
Use `hook_civicrm_managed` for "custom group extends" optionValues

### PR DESCRIPTION
**Pull request by colemanw**
Meet the new APIv4-based Managed Entities :sunglasses: 

With this hook, we can loop through all existing EckEntityTypes, and generate whatever related data we want for them in a declarative fashion. In this example, I'm switching to using that method for the `cg_extend_objects` option value.

Note that this is covered by the unit test `\api\v4\EckEntity\EckEntityTest::testCreateEntityType()`

**Advantages:**
- If we had been doing it this way from the beginning, there would be no upgrade needed for switching the option values from `EckFoo` to `Eck_Foo` as the records get refreshed during every upgrade and every system flush.
- Because of this, I was able to remove the upgrade step which makes that change, as the old records just need to be deleted.
- In the future when we fix the bug related to the `__callStatic` method in the `description` field we will not need an upgrade script to update the `description` of these option values. Changing the declaration will trigger it to happen automatically.
- In the near future we can use this same technique to declare a saved search & search display for every entity type!

**One disadvantage:**
This works great for new installs, but unfortunately there is a problem for upgrading existing installs. As you might have guessed, you'll need a manual step to upgrade your client once this PR is merged & deployed to them. I tried adding an upgrader step in `CRM_Eck_Upgrader` to do this automatically, but unfortunately it didn't work because `hook_civicrm_managed` gets called *before* the upgrader runs. This is the upgrade code which you'll need to execute manually before you deploy this to your client:
```php
\Civi\Api4\OptionValue::delete(FALSE)
  ->addWhere('option_group_id:name', '=', 'cg_extend_objects')
  ->addWhere('name', 'LIKE', 'civicrm_eck_%')
  ->execute();
```

### CODE REVIEW

**Comment by jensschuppe** [comment]
Any reason why running the following in the upgrader won't work reliably?

```php
/**
 * Remove old-format entries in the "cg_extend_objects" OptionGroup.
 * The correct entries are being created by
 * @see eck_civicrm_managed().
 */
$eck_entity_types = \Civi\Api4\EckEntityType::get()
  ->execute()
  ->indexBy('id')
  ->column('name');
$eck_entity_types = array_map(function ($value) {
  return 'Eck' . $value;
}, $eck_entity_types);
$cg_extend_entity_types = \Civi\Api4\OptionValue::delete(FALSE)
  ->addWhere('option_group_id:name', '=', 'cg_extend_objects')
  ->addWhere('value', 'IN', $eck_entity_types)
  ->execute();
```

This would delete all OptionValue entries with the old prefix regardless of when it runs, no?

And a question regarding the `managed` hook: How does it know which OptionValues to delete, is this determined by comparing entities in a namespace defined by the `module` and `name` properties?

Aside: Can this hook then also be used to ensure the OptionGroup for subtypes being there (replacing @bjendres' `CustomData` thing that's currently syncing this OptionGroup when installing)?

**Comment by colemanw** [comment]
> Any reason why running the following in the upgrader won't work reliably?

Yes, I just tried it and the problem is that `hook_civicrm_managed` runs **first** before the upgrader. So it tries to create a duplicate option value and hits a unique constraint. The upgrade fails with:

```
  [is_error] => 1
  [error_message] => API error: Value already exists in the database on OptionValue.create
```

Under normal circumstances, I would say we need to somehow solve this problem and spend hours working 
through the upgrade code to figure out how to change the order of operations. However, there is only one site in the world using this extension! All you have to do is delete the one record in their database and everything will work :)

**Comment by colemanw** [comment]
Actually @jensschuppe it just occurred to me that for sites running before we changed the entity names, there will be no conflict, because the old option value with have a value like `EckFoo` and the new one we insert via `hook_civicrm_managed` will have a value like `Eck_Foo` so all we have to do is change the upgrader to delete the old record. I've pushed up a change to the upgrader to delete instead of rename the option values.

**Comment by jensschuppe** [comment]
That's basically what I was saying in [my comment above](https://github.com/systopia/de.systopia.eck/pull/30#issuecomment-1057998805) :wink: Thanks!

Btw, am I right with those two other things?

>And a question regarding the `managed` hook: How does it know which OptionValues to delete, is this determined by comparing entities in a namespace defined by the `module` and `name` properties?

>Aside: Can this hook then also be used to ensure the OptionGroup for subtypes being there (replacing @bjendres' CustomData thing that's currently syncing this OptionGroup when installing)?

**Comment by colemanw** [comment]
Sorry, that took me a while to figure out :) You were right.

> And a question regarding the `managed` hook: How does it know which OptionValues to delete, is this determined by comparing entities in a namespace defined by the `module` and `name` properties?

The `Managed` system works by keeping records in the `civicrm_managed` database table. It stores the `name` of the managed item (as defined by what the hook returns) and the `id` of the record which has been inserted into the database. In this case the `name` is defined by `'name' => 'cg_extends:' . $type['name'],` - that's kind of arbitrary, it just needs to be unique and stable.

> Aside: Can this hook then also be used to ensure the OptionGroup for subtypes being there (replacing @bjendres' CustomData thing that's currently syncing this OptionGroup when installing)?

Certainly, yes. I think it will pose a similar upgrade issue though.

**Pull request merged**
