### PR TITLE
Remove APIv3

### PR DESCRIPTION
**Pull request by colemanw**
As the great @eileenmcnaughton once said, "If it isn't tested, it doesn't exist."
Well, this extension has no APIv3 tests, so it might as well not exist :)
Removing it simplifies everything going forward.

### CODE REVIEW

**Comment by colemanw** [comment]
I realized this PR is premature because this extension is using APIv3 internally to access both `EckEntityType` and `Eck*`, so we need to clean up those api calls first. #15 is a start.

**Comment by jensschuppe** [comment]
Removing API v3 for the entities this extension provides involves making them inaccessible via the REST API with v3, right @colemanw? I'm not sure about the status of API v4's REST interface, but am inclined to continue exposing those entities via the REST API v3 for the time being.

However, I agree that internally, all entities should be accessed using API v4, which #15 is taking care of.

**Comment by colemanw** [comment]
@jensschuppe @bjendres work on the v4 REST API was recently completed:
https://docs.civicrm.org/dev/en/latest/api/v4/rest/

**Comment by bjendres** [comment]
That's good to hear, but we still have a lot of communication infrastructure based on APIv3, so it'll be nice if it could stick around for a little longer. Feel free to mark as deprecated, though.

**Comment by colemanw** [comment]
Ok, just keep in mind that it has no unit tests, so unless you add some, it's not stable.

@bjendres @jensschuppe could one of you please merge #13 so we have unit test coverage for APIv4. That's a start toward getting this extension stable.

**Comment by jensschuppe** [comment]
Also, the "legacy" authentication method (`key` and `api_key`) for the APIv4 REST endpoint will only be available with CiviCRM 5.47, as per civicrm/civicrm-core#19727, which a lot of code talking to CiviCRM via REST depends on.

**Comment by jensschuppe** [comment]
Since we have a branch ([`release/1.x`](https://github.com/systopia/de.systopia.eck/tree/release/1.x)) with APIv3 still working for some actions (`get`, `getfields`), feel free to reopen this PR for the `master` branch, @colemanw.

**Comment by jensschuppe** [comment]
There are still two occurences of `civicrm_api3()` calls:

```
Targets
    Occurrences of 'civicrm_api3' in Directory sites/default/files/civicrm/ext/de.systopia.eck
Found Occurrences in Directory sites/default/files/civicrm/ext/de.systopia.eck  (11 usages found)
    Unclassified  (11 usages found)
        civicrm_test  (11 usages found)
            sites/default/files/civicrm/ext/de.systopia.eck/CRM/Eck/Form  (3 usages found)
                EckSubtype.php  (2 usages found)
                    52 $this->_subType = civicrm_api3(
                    174 civicrm_api3('OptionValue', 'create', array_merge($this->_subType, [
                EntityType.php  (1 usage found)
                    186 $count = civicrm_api3('EckEntityType', 'getcount', [
```
(leaving alone those in the `CRM_Eck_CustomData` class which I created an issue for in systopia/Custom-Data-Helper#2)

**Comment by colemanw** [comment]
The 'OptionValue' api call isn't a problem wrt this PR. But you're right the 'EckEntityType' call needs to be updated because we are removing that api.

**Comment by colemanw** [comment]
@jensschuppe fixed.

**Comment by colemanw** [comment]
Ok I've looked at those, and found that:
1. `civicrm/admin/eck/entity-type?reset=1&action=update&type=FooBar` is working for me. I think it may be broken for you due to the api entity name change (and not due to this PR). Try updating your custom group `extends` column from `EckFooBar` to `Eck_FooBar`.
2. Ditto for `civicrm/admin/eck/subtype?reset=1&action=update&subtype=1`.
3. Fixed `civicrm/eck/entity/list?reset=1&type=FooBar`
4. Fixed `civicrm/eck/entity?reset=1&action=view&type=FooBar&id=1`

**Comment by jensschuppe** [comment]
You're right, the `cg_extend_objects` OptionGroup entries and `extends` properties of CustomGroups extending ECK entities will have to be updated, which I added an upgrade funtion for in d988d14971bbc3bd733a227ccfaba1095f1fc2e2.

This is now working. Thanks @colemanw for your work on that!

**Pull request merged**
